### ISSUE TITLE
Napravite vise zivota

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG053-raining-cats-and-dogs#2]
- Stavite da igrac na pocetku ima vise zivota
- Da zelena kocka daje zivot (plava i dalje da oduzima)

**Comment by ajvaznevena** [comment]
Napravila sam da se igrica igra na bodove, ne na zivote. Dodala sam jos jednu plavu kocku kako bi igra bila izazovnija
