### ISSUE TITLE
Ubrzajte kretanje igraca

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG053-raining-cats-and-dogs#3]
Stavite da igrac brze prelazi sa polja na polje

**Comment by ajvaznevena** [comment]
Ubrzala sam kretanje igraca tri puta, ali se zbog toga promenila pozicija na poljima. Napravila sam nove koordinate "granice", izmenila ih za igraca. Zbog toga sam morala da izmenim koordinate za padajuce objekte takodje, sto sam i uradila. Ali nisam uspela da te napravim koliziju novodobijenih koordinata, tacnije nije radila za sve slucajeve, tako da sam kod ostavila nepromenjen sa trenutnom brzinom.
